name: Build Xposed APK
on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # Cho phép bấm chạy thủ công từ giao diện Web

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
        
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Thiết lập Gradle ổn định để build Android Gradle Plugin 8.1.1
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: 8.2.1

    # Tạo lại tệp Wrapper tương thích trực tiếp trên máy chủ GitHub
    - name: Generate Gradle Wrapper
      run: gradle wrapper --gradle-version 8.2.1

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Debug APK
      run: ./gradlew assembleDebug

    - name: Upload Finished APK
      uses: actions/upload-artifact@v4
      with:
        name: FmsSupport_v1.0
        path: app/build/outputs/apk/debug/app-debug.apk
